site_name: python-nomad
theme: readthedocs
repo_url: https://github.com/jrxfive/python-nomad/
repo_name: GitHub
google_analytics: ['UA-36723568-3', 'mkdocs.org']
pages:
- Home: 'index.md'
- Nomad:
   - Examples: 'nomad/examples.md'
- Api:
   - Agent: 'api/agent.md'
   - Allocation: 'api/allocation.md'
   - Allocations: 'api/alocations.md'
   - Client: 'api/client.md'
   - Deployment: 'api/deployment.md'
   - Deployments: 'api/deployments.md'
   - Evaluations: 'api/evaluations.md'
   - Evaluation: 'api/evaluation.md'
   - Job: 'api/job.md'
   - Jobs: 'api/jobs.md'
   - Metrics: 'api/metrics.md'
   - Node: 'api/node.md'
   - Nodes: 'api/nodes.md'
   - Regions: 'api/regions.md'
   - Status: 'api/status.md'
   - System: 'api/system.md'
   - Acl: 'api/acl.md'
   - Namespace: 'api/namespace.md'
   - Namespaces: 'api/namespaces.md'
   - Sentinel: 'api/sentinel.md'
   - Validate: 'api/validate.md'
- Contributing: 'CONTRIBUTING.md'
